# ========================
# APPLICATION
# ========================
spring.application.name=Pf.auth-service
server.port=8081

# ========================
# DATASOURCE (PostgreSQL)
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/pf_auth
spring.datasource.username=postgres
spring.datasource.password=2005
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# HIKARICP (CONNECTION POOL)
# ========================
# Giúp quản lý connection mượt mà và tối ưu hiệu suất hơn
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

# ========================
# JPA / HIBERNATE
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Tối ưu hóa việc query/insert/update db (Batching)
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# ========================
# LOGGING
# ========================
logging.level.root=INFO
logging.level.com.Pf.auth_service=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
